services:
  # --- LE CERVEAU (PHP 8.4 + Symfony) ---
  app:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: dating_php
    volumes:
      - ./api:/var/www/html:rw
      - /var/www/html/var/cache
      - /var/www/html/var/log
    ports:
      - "8000:8000"
    command: php -S 0.0.0.0:8000 -t public
    environment:
      - APP_ENV=dev
      - XDEBUG_MODE=off
      - PHP_CLI_SERVER_WORKERS=10
      - PHP_OPCACHE_VALIDATE_TIMESTAMPS=0
    restart: unless-stopped  
    networks:
      - dating_network

  # --- L'INTERFACE REACT (Node.js) ---
  frontend:
    image: node:20-alpine
    container_name: dating_react
    working_dir: /app
    volumes:
      - ./frontend:/app:rw
    ports:
      - "3000:3000"
    # Note : npm install peut être long la première fois
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app
    networks:
      - dating_network

  # --- LA BASE DE DONNÉES (PostgreSQL) ---
  database:
    image: postgres:16-alpine
    container_name: dating_db
    environment:
      POSTGRES_DB: dating_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped  
    networks:
      - dating_network

  # --- L'INTERFACE BDD (PGAdmin) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: dating_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@dating.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    restart: unless-stopped 
    networks:
      - dating_network

  # --- LE CACHE (Redis) ---
  redis:
    image: redis:alpine
    container_name: dating_redis
    restart: unless-stopped  
    networks:
      - dating_network

  # --- LE TEST D'EMAILS (Mailhog) ---
  mailhog:
    image: mailhog/mailhog
    container_name: dating_mailhog
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Interface Web
    restart: unless-stopped  
    networks:
      - dating_network

networks:
  dating_network:
    driver: bridge

volumes:
  db-data:
  cache_data:
  log_data: