nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['http://localhost:3000'] # On autorise uniquement le front React
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization'] # Très important pour le Bearer Token !
        max_age: 3600
    paths:
        '^/api/': # On applique ces règles uniquement aux routes qui commencent par /api
            allow_origin: ['http://localhost:3000']
            allow_headers: ['Content-Type', 'Authorization']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600