<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260223090341 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX ide_lookup_idx');
        $this->addSql('DROP INDEX translations_lookup_idx');
        $this->addSql('ALTER TABLE ext_translations ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE ext_translations ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('CREATE UNIQUE INDEX lookup_unique_idx ON ext_translations (foreign_key, locale, object_class, field)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP INDEX lookup_unique_idx');
        $this->addSql('ALTER TABLE ext_translations ALTER id SET DEFAULT nextval(\'ext_translations_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE ext_translations ALTER id DROP IDENTITY');
        $this->addSql('CREATE INDEX ide_lookup_idx ON ext_translations (object_class, field, foreign_key)');
        $this->addSql('CREATE INDEX translations_lookup_idx ON ext_translations (locale, object_class, foreign_key)');
    }
}
