<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260205142637 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE member_memo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, author_id INT NOT NULL, target_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_57C2BC76F675F31B ON member_memo (author_id)');
        $this->addSql('CREATE INDEX IDX_57C2BC76158E0B66 ON member_memo (target_id)');
        $this->addSql('ALTER TABLE member_memo ADD CONSTRAINT FK_57C2BC76F675F31B FOREIGN KEY (author_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE member_memo ADD CONSTRAINT FK_57C2BC76158E0B66 FOREIGN KEY (target_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE member_memo DROP CONSTRAINT FK_57C2BC76F675F31B');
        $this->addSql('ALTER TABLE member_memo DROP CONSTRAINT FK_57C2BC76158E0B66');
        $this->addSql('DROP TABLE member_memo');
    }
}
